config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  resources :exercises do
    member do
      resources :exercise_steps
    end
  end
  resources :equipment
  resources :units

  namespace :telegram do
    get "/programs" => 'telegram_api1#programs'
    get "/details" => 'telegram_api1#details'
    get "sign" => 'telegram_api1#sign'
    get "/unsign" => 'telegram_api1#unsign'
    get "/mysigns" => 'telegram_api1#mysigns'
    get "/today" => 'telegram_api1#today'
    get "/day" => 'telegram_api1#day'
    get "schedule" => 'telegram_api1#schedule'
  end

  resources :programs
  resources :program_days
  resources :day_exercises

  post "api/update_order" => 'api#update_order'
  post "api/clone_program_day" => 'api#clone_program_day'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :unit
  has_many :day_exercises
  has_many :exercise_steps
  has_and_belongs_to_many :program_days, :class_name => 'ProgramDay', :join_table => :day_exercises
  has_and_belongs_to_many :equipment

  validates :title, presence: true
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :set_chapter
  before_action :get_item, only: [:show, :edit, :destroy, :update]

  def index
    @items = Exercise.all.to_a.sort_by{|i| i.title}
  end

  def create
    @item = Exercise.new(exercise_params)
    if @item.save
      redirect_to exercises_path, notice: 'Создано'
    else
      render action: 'new', error: 'Ошибка при добавлении'
    end
  end

  def edit
    @chapters.push({title: "Редактировать \"#{@item.title}\"", src: "#"})
  end

  def update
    if @item.update(exercise_params)
      redirect_to edit_exercise_path(@item), notice: 'Сохранено'
    else
      render action: 'edit', error: 'Ошибка сохранения'
    end
  end

  def new
    @item = Exercise.new
    @chapters.push({title: "Добавить упражнение", src: "#"})
  end

  def destroy
    if @item.destroy
      redirect_to exercises_path(@item), notice: 'Удалено'
    else
      render action: 'edit', error: 'Ошибка удаления'
    end
  end

  def set_chapter
    @chapters = [{title: 'Упражнения', src: exercises_path}]
  end

  private

  def exercise_params
    params[:exercise].permit!
  end

  def get_item
    @item = Exercise.find(params[:id])
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.slim
= render partial: 'exercises/tabs'

.row.top30
  .col.s12
    = form_for(@item) do |f|
      .row
        .col.s12
          .input-field
            = f.text_field :title
            label for='title' Название

      .row
        .col.s12
          .input-field
            = f.text_area :description, class: 'materialize-textarea'
            label for='description' Описание
      .row
        .col.s12
          .input-field
            = f.collection_select :unit_id, Unit.all, :id, :title,
                                  {selected: @item.unit_id, include_blank: true}, {class: ''}
            label for='unit_id' Единица измерения

      .row
        .col.s12
          .input-field
            = f.collection_select :equipment_ids, Equipment.all, :id, :title,
                                  {selected: @item.equipment_ids, include_blank: true}, {multiple: true, class: ''}
            label for='equipment_ids' Инвентарь


      .row
        .col.s8
          .input-field
            button.btn.waves-effect.waves-light name="action" type="submit"
              | Сохранить
              i.material-icons.right send
            a.btn-flat href="#{exercises_path}" Отмена
        - unless @item.new_record?
          .col.s4.right
            .input-field
              =link_to 'Удалить', exercise_path(@item), method: :delete, class: 'btn waves-effect waves-light red lighten-2', data: {confirm: 'Подтвердите удаление'}

app/views/exercises/_tabs.html.slim
.row
  ul.tabs.z-depth-1
    li.tab
      a.active href=edit_exercise_path(@item) target="_blank" Общая
    - disabled = 'disabled' if @item.new_record?
    li.tab class=disabled
      a href=exercise_steps_path(@item)  target="_blank" Описание

app/views/exercises/edit.html.slim
= render partial: 'exercises/form'

app/views/exercises/index.html.slim
.row
  .col.s8
    h5.header Упражнения
  .col.s4
    a.btn.waves-effect.top10.right.waves-light href=new_exercise_path Cоздать
ul
  - @items.each do |item|
    li: a href=edit_exercise_path(item) =item.title